Fix sections not showing up on instructor search
ucsb-cs156-f23/proj-courses-f23-7pm-1 pull request #20
Opened 2023-11-19 22:31 UTC by rdoumeth

Fixed search by instructor functionality by showing all sections taught in a class, regardless of whether the professor is the TA or not. 

<img width="1512" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/assets/86987744/9631cb45-5336-4abb-8f2d-33e30c7c625c">

Closes #9

2023-11-30 04:51 UTC, pconrad requested changes
It still doesn't seem to be working properly.

Look up CMPSC 156 for W22. There were two TAs, LU and HEFFERNAN

If you search for either of them, only the 5pm section shows up.  All three should show up.

As another example, consider CMPSC 5A.  There are two sections:
<img width="1515" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/assets/1119017/87b81dac-72d3-4c5b-abe2-ec57c2c8ea48">


But search for TANNA and only one shows up:

<img width="1383" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/assets/1119017/3c0760ca-56bf-4bf0-8bbe-a7cc62c45ccf">


So the bug still isn't fixed; just replaced with a different bug.

2023-11-30 19:26 UTC, rdoumeth commented on frontend/src/main/components/InstructorSearchTableBase.js
> +      {
I actually based my code on SectionsTableBase which doesn't have that column hidden, for some reason. I'll do that change right now.

2023-12-01 18:56 UTC, pconrad commented on frontend/src/main/components/InstructorSearchTableBase.js
> +// Stryker disable StringLiteral, ArrayDeclaration
Please, no, ... this is too broad.

Use `// Stryker disable all` plus `// Stryker restore all` around the smallest section of code possible.

2023-12-01 18:57 UTC, pconrad commented on frontend/src/main/components/InstructorSearchTableBase.js
> +                      // Stryker disable next-line ObjectLiteral
There is no need for a stryker exception here.  You can write a test for this quite easily; there are many examples in our code bases.  You want to look for something like `expect(thing).toHaveAttribute('style'...`

2023-12-01 18:58 UTC, pconrad requested changes
The code finally works!

Now that it does, there are a few things in the code that need to be fixed.

2023-12-05 20:54 UTC, pconrad approved these changes
LGTM

2023-12-05 20:54 UTC, merged