Added Dropdown to choose Schedule to Add Course
ucsb-cs156-f23/proj-courses-f23-7pm-1 pull request #38
Opened 2023-11-30 14:42 UTC by mageswarankk

This commit replaces a textbox (prompt for Personal Schedule ID) with a dropdown to choose a Personal Schedule from a list with names when adding a Course to a Personal Schedule.

NOTE: There needs to be 2 schedules and the user has to click between them in the dropdown choice for it to work; it doesn't seem like (I might be wrong about this) other groups have found a workaround for this; apart from this Bug, the feature works as intended.

Deployed at https://proj-courses-mageswarankk-dev.dokku-09.cs.ucsb.edu/
at page courses/create

![image](https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/assets/73411210/448b491a-c94a-4b24-88b7-c248e3547325)

Closes #8

2023-11-30 17:47 UTC, pconrad requested changes
Ok, so there are so many files unrelated to the PR that have minor whitespace changes here that it's really difficult to find the actual code changes.

In some organizations, they have a zero tolerance policy for this.  I generally am chill about it when it's one or two files, but this is way over the top.

Please either:
* Fix this branch to have only the changes to the files that are needed for the new functionality, OR
* Make a new PR that has only those changes.

One way to do the first approach is this:

```
git fetch
git checkout km-pscoursecreate-dropdown
git pull origin mkm-pscoursecreate-dropdown
git reset --soft origin/main
git status
```

You should now see all of the files that were modified, showing up in "red" as files that have been modified by not yet commited.  Now, go through, and for each file that does NOT pertain to the PR, restore it to it's original version.  For example:

```
git checkout frontend/.babelrc
git status
git checkout frontend/.eslintrc.json
git status
```
etc.   Each time you do the `git checkout filename` it should restore that file to what is in the main branch, discarding the changes.  DO NOT do this for the files that actually HAVE changes that are important to the PR.   Instead, for those files, use:

```
git add frontend/src/main/components/Courses/CourseForm.js
git status
```

For each, you should see that the file turns "green" because it's going to be added to the next commit.

When done, `git status` should show you ONLY the files that you want in the PR.
Then, do a new commit:

```
git commit -m "km-add dropdown to choose schedule when adding a course"
```

Then you need to do:

```
git push origin km-pscoursecreate-dropdown -f
```

The `-f` is needed because you are "rewriting history".

Good luck!

2023-11-30 18:45 UTC, mageswarankk commented
Yeah, I was failing an `npx eslint --max-warnings 0 .` test, and so I ran it with the `--fix` flag which went through and fixed stuff from the entire repository. All the unnecessary changes should be reverted now.

2023-12-01 19:01 UTC, pconrad commented on frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
>      //expect(setQuarter).toBeCalledWith("20124"); //need this and axiosMock below?
Even though this was in the original, pleas remove commented out code when you find it.
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-12-01 19:02 UTC, pconrad requested changes
So much commented out code.

I wonder: did I not go over this enough?  

https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-12-01 19:02 UTC, pconrad commented on frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
> +    //expect(setQuarter).toBeCalledWith("20124"); //need this and axiosMock below?
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-12-05 20:55 UTC, pconrad approved these changes
LGTM

2023-12-05 21:01 UTC, merged